### ISSUE TITLE
Auth system

### ISSUE THREAD

**Issue by JanLikar** [JanLikar/covid#1]
- [x] Generate mnemonic passwords using wordlist from http://world.std.com/~reinhold/diceware.html (I guess 8 words should be enough)
- [x] Login / password generation pages
- [x] Session cookies
- [x] Pyramid auth setup (Auth policies)

**Comment by persho** [comment]
I found this for Diceware, what do you think? I cannot seem to see a clear way to set number of words, not sure if I am blind https://diceware.readthedocs.io/en/stable/api.html @JanLikar

**Comment by JanLikar** [comment]
Sure, why not, but I too can't find a way to generate a specific number of words.

**Comment by persho** [comment]
@JanLikar Done, I made a MR, please review and please make some comments to teach me how to write better code. :)

**Comment by persho** [comment]
I had some conflicts merging your changes, so I am sure you will too. Try to resolve them and maybe lets talk about how to avoid them.
