### ISSUE TITLE
Add public comments

### ISSUE THREAD

**Issue by persho** [JanLikar/covid#33]
@JanLikar I was thinking, say someone places a marker on a specific building because they were inside of it, but then the building manager cleans up the building etc, and in a week it is confirmed sterile. We need to allow mechanism for people to report on markers. 

We can use third party plugins like disquss, but we would need to make the URL change for each marker, so there would have to be marker ID shown in URL so disqus could change for each marker. We could then just pop disqus js code to the left pane.

Custom solution would be something like below:

1. On public view, without logging in, when user clicks on a marker, add a small link, add comment.
2. When user clicks add comment, open a commenting form in the left panel. Below the form show all comments.
- Form should have optional name, and message, and date+time. When showing show time of the message
NOTE: Potential issue, we need 2 forms on the same page, because we have login form on front page, not sure how to add the second form.
3. Make the left pane scroll if there are many comments comments

**Comment by JanLikar** [comment]
"Commento" is a nice alternative. I'd rather not implement this by myself

**Comment by JanLikar** [comment]
You did great, thank you!
